# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='is_choosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='avatar',
            unique_together=set([('user', 'avatar_name', 'avatar_password', 'avatar_email', 'created_at', 'is_choosen')]),
        ),
    ]
